export const keys = [
  {
    id: 5212,
    key_category_id: 61,
    code: "Y",
    label: "Y",
    description: null,
    created_at: "2021-12-28T09:52:59.133Z",
    updated_at: "2022-12-16T10:18:29.956Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyY",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5214,
    key_category_id: 61,
    code: "Z",
    label: "Z",
    description: null,
    created_at: "2021-12-28T09:52:59.149Z",
    updated_at: "2022-12-16T10:18:29.972Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyZ",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5199,
    key_category_id: 61,
    code: "A",
    label: "A",
    description: null,
    created_at: "2021-12-28T09:52:59.022Z",
    updated_at: "2022-12-16T10:18:29.845Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyA",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5203,
    key_category_id: 61,
    code: "B",
    label: "B",
    description: null,
    created_at: "2021-12-28T09:52:59.057Z",
    updated_at: "2022-12-16T10:18:29.879Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyB",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5216,
    key_category_id: 61,
    code: "C",
    label: "C",
    description: null,
    created_at: "2021-12-28T09:52:59.165Z",
    updated_at: "2022-12-16T10:18:29.989Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyC",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5206,
    key_category_id: 61,
    code: "D",
    label: "D",
    description: null,
    created_at: "2021-12-28T09:52:59.084Z",
    updated_at: "2022-12-16T10:18:29.906Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyD",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5202,
    key_category_id: 61,
    code: "E",
    label: "E",
    description: null,
    created_at: "2021-12-28T09:52:59.049Z",
    updated_at: "2022-12-16T10:18:29.870Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyE",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5200,
    key_category_id: 61,
    code: "F",
    label: "F",
    description: null,
    created_at: "2021-12-28T09:52:59.031Z",
    updated_at: "2022-12-16T10:18:29.853Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyF",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5208,
    key_category_id: 61,
    code: "G",
    label: "G",
    description: null,
    created_at: "2021-12-28T09:52:59.102Z",
    updated_at: "2022-12-16T10:18:29.923Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyG",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5219,
    key_category_id: 61,
    code: "H",
    label: "H",
    description: null,
    created_at: "2021-12-28T09:52:59.191Z",
    updated_at: "2022-12-16T10:18:30.025Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyH",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5205,
    key_category_id: 61,
    code: "I",
    label: "I",
    description: null,
    created_at: "2021-12-28T09:52:59.075Z",
    updated_at: "2022-12-16T10:18:29.897Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyI",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5210,
    key_category_id: 61,
    code: "J",
    label: "J",
    description: null,
    created_at: "2021-12-28T09:52:59.117Z",
    updated_at: "2022-12-16T10:18:29.940Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyJ",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5224,
    key_category_id: 61,
    code: "K",
    label: "K",
    description: null,
    created_at: "2021-12-28T09:52:59.236Z",
    updated_at: "2022-12-16T10:18:30.076Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyK",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5211,
    key_category_id: 61,
    code: "L",
    label: "L",
    description: null,
    created_at: "2021-12-28T09:52:59.125Z",
    updated_at: "2022-12-16T10:18:29.948Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyL",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5201,
    key_category_id: 61,
    code: "M",
    label: "M",
    description: null,
    created_at: "2021-12-28T09:52:59.040Z",
    updated_at: "2022-12-16T10:18:29.862Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyM",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5222,
    key_category_id: 61,
    code: "N",
    label: "N",
    description: null,
    created_at: "2021-12-28T09:52:59.217Z",
    updated_at: "2022-12-16T10:18:30.056Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyN",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5220,
    key_category_id: 61,
    code: "O",
    label: "O",
    description: null,
    created_at: "2021-12-28T09:52:59.200Z",
    updated_at: "2022-12-16T10:18:30.036Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyO",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5209,
    key_category_id: 61,
    code: "P",
    label: "P",
    description: null,
    created_at: "2021-12-28T09:52:59.110Z",
    updated_at: "2022-12-16T10:18:29.931Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyP",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5218,
    key_category_id: 61,
    code: "Q",
    label: "Q",
    description: null,
    created_at: "2021-12-28T09:52:59.183Z",
    updated_at: "2022-12-16T10:18:30.014Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyQ",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5217,
    key_category_id: 61,
    code: "R",
    label: "R",
    description: null,
    created_at: "2021-12-28T09:52:59.175Z",
    updated_at: "2022-12-16T10:18:29.999Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyR",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5215,
    key_category_id: 61,
    code: "S",
    label: "S",
    description: null,
    created_at: "2021-12-28T09:52:59.157Z",
    updated_at: "2022-12-16T10:18:29.980Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyS",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5223,
    key_category_id: 61,
    code: "T",
    label: "T",
    description: null,
    created_at: "2021-12-28T09:52:59.227Z",
    updated_at: "2022-12-16T10:18:30.066Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyT",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5221,
    key_category_id: 61,
    code: "U",
    label: "U",
    description: null,
    created_at: "2021-12-28T09:52:59.208Z",
    updated_at: "2022-12-16T10:18:30.045Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyU",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5204,
    key_category_id: 61,
    code: "V",
    label: "V",
    description: null,
    created_at: "2021-12-28T09:52:59.066Z",
    updated_at: "2022-12-16T10:18:29.887Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyV",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5207,
    key_category_id: 61,
    code: "W",
    label: "W",
    description: null,
    created_at: "2021-12-28T09:52:59.093Z",
    updated_at: "2022-12-16T10:18:29.914Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyW",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5213,
    key_category_id: 61,
    code: "X",
    label: "X",
    description: null,
    created_at: "2021-12-28T09:52:59.142Z",
    updated_at: "2022-12-16T10:18:29.964Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "KeyX",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6001,
    key_category_id: 63,
    code: "LSHIFT",
    label: "Left shift",
    description: null,
    created_at: "2021-12-28T09:53:02.738Z",
    updated_at: "2022-12-16T10:18:31.972Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: "shift_left",
    jsCode: "ShiftLeft",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5464,
    key_category_id: 63,
    code: "MOD_LSFT",
    modCode: "LS",
    label: "Left Shift",
    description: null,
    created_at: "2021-12-28T09:53:02.723Z",
    updated_at: "2022-12-16T10:18:31.964Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: false,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6002,
    key_category_id: 63,
    code: "RSHIFT",
    label: "Right shift",
    description: null,
    created_at: "2021-12-28T09:53:02.686Z",
    updated_at: "2022-12-16T10:18:31.939Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: "shift_right",
    jsCode: "ShiftRight",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5476,
    key_category_id: 63,
    code: "MOD_RSFT",
    modCode: "RS",
    label: "Right Shift",
    description: null,
    created_at: "2021-12-28T09:53:02.921Z",
    updated_at: "2022-12-16T10:18:32.075Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: false,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6003,
    key_category_id: 63,
    code: "LCTRL",
    label: "Left Ctrl",
    description: null,
    created_at: "2021-12-28T09:53:02.894Z",
    updated_at: "2022-12-16T10:18:32.058Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "control",
    tag: null,
    glyph: null,
    jsCode: "ControlLeft",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5470,
    key_category_id: 63,
    code: "MOD_LCTL",
    modCode: "LC",
    label: "Left Control",
    description: null,
    created_at: "2021-12-28T09:53:02.833Z",
    updated_at: "2022-12-16T10:18:32.025Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: false,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6004,
    key_category_id: 63,
    code: "RCTRL",
    label: "Right Ctrl",
    description: null,
    created_at: "2021-12-28T09:53:02.936Z",
    updated_at: "2022-12-16T10:18:32.084Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "control",
    tag: null,
    glyph: null,
    jsCode: "ControlRight",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5468,
    key_category_id: 63,
    code: "MOD_RCTL",
    modCode: "RC",
    label: "Right Control",
    description: null,
    created_at: "2021-12-28T09:53:02.806Z",
    updated_at: "2022-12-16T10:18:32.006Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: false,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6005,
    key_category_id: 63,
    code: "LALT",
    label: "Left Alt",
    description: null,
    created_at: "2021-12-28T09:53:02.663Z",
    updated_at: "2022-12-16T10:18:31.921Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "option",
    tag: null,
    glyph: null,
    jsCode: "AltLeft",
    url: null,
    os: {
      osx: {
        glyph: "option_left",
        label: "Left Option",
      },
      others: {
        label: "Left Alt",
      },
    },
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5475,
    key_category_id: 63,
    code: "MOD_LALT",
    modCode: "LA",
    label: "Left alt",
    description: null,
    created_at: "2021-12-28T09:53:02.907Z",
    updated_at: "2022-12-16T10:18:32.067Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: false,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: {
      osx: {
        label: "Left Option",
      },
      others: {
        label: "Left Alt",
      },
    },
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6006,
    key_category_id: 63,
    code: "RALT",
    label: "Right Alt",
    description: "Also known as AltGr.",
    created_at: "2021-12-28T09:53:02.786Z",
    updated_at: "2022-12-16T23:38:29.817Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "altgr option",
    tag: null,
    glyph: null,
    jsCode: "AltRight",
    url: null,
    os: {
      osx: {
        glyph: "option_right",
        label: "Right Option (macOS)",
      },
      others: {
        label: "Right Alt",
      },
    },
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5460,
    key_category_id: 63,
    code: "MOD_RALT",
    modCode: "RA",
    label: "Right alt",
    description: "Right Alt, also known as AltGr.",
    created_at: "2021-12-28T09:53:02.675Z",
    updated_at: "2022-12-16T23:38:29.778Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: false,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: {
      osx: {
        glyph: "Right Option",
        label: "Right Option",
      },
      others: {
        label: "Right Alt",
      },
    },
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6007,
    key_category_id: 63,
    code: "LGUI",
    label: "Left Gui",
    description: null,
    created_at: "2021-12-28T09:53:02.712Z",
    updated_at: "2022-12-16T10:18:31.956Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "gui cmd command meta windows super",
    tag: null,
    glyph: null,
    jsCode: "MetaLeft",
    url: null,
    os: {
      osx: {
        glyph: "command_left",
        label: "Left Command",
      },
      win: {
        glyph: "windows_left",
        label: "Left Windows",
      },
      linux: {
        glyph: "linux_left",
        label: "Left Meta",
      },
    },
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5473,
    key_category_id: 63,
    code: "MOD_LGUI",
    modCode: "LG",
    label: "Left GUI",
    description: null,
    created_at: "2021-12-28T09:53:02.879Z",
    updated_at: "2022-12-16T10:18:32.050Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: false,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: {
      osx: {
        label: "Left Command",
      },
      win: {
        label: "Left Windows",
      },
      linux: {
        label: "Left Meta",
      },
    },
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6008,
    key_category_id: 63,
    code: "RGUI",
    label: "Right Gui",
    description: null,
    created_at: "2021-12-28T09:53:02.847Z",
    updated_at: "2022-12-16T10:18:32.033Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "gui cmd command meta windows super",
    tag: null,
    glyph: null,
    jsCode: "MetaRight",
    url: null,
    os: {
      osx: {
        glyph: "command_right",
        label: "Right Command",
      },
      win: {
        glyph: "windows_right",
        label: "Right Windows",
      },
      linux: {
        glyph: "linux_right",
        label: "Right Meta",
      },
    },
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5462,
    key_category_id: 63,
    code: "MOD_RGUI",
    modCode: "RG",
    label: "Right GUI",
    description: null,
    created_at: "2021-12-28T09:53:02.698Z",
    updated_at: "2022-12-16T10:18:31.947Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: false,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: {
      osx: {
        label: "Right Command",
      },
      win: {
        label: "Right Windows",
      },
      linux: {
        label: "Right Meta",
      },
    },
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5589,
    key_category_id: 81,
    code: "SPACE",
    label: "Space",
    description: null,
    created_at: "2021-12-28T09:53:04.184Z",
    updated_at: "2022-12-16T10:18:33.007Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "spaceonly",
    tag: null,
    glyph: "space",
    jsCode: "Space",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 1,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5577,
    key_category_id: 81,
    code: "ENTER",
    label: "Enter",
    description: null,
    created_at: "2021-12-28T09:53:04.131Z",
    updated_at: "2022-12-16T10:18:32.968Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "Enter Return",
    tag: null,
    glyph: "enter",
    jsCode: "Enter",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 2,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5580,
    key_category_id: 81,
    code: "BACKSPACE",
    label: "Backspace",
    description: null,
    created_at: "2021-12-28T09:53:04.171Z",
    updated_at: "2022-12-16T10:18:32.996Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "space Backspace",
    tag: null,
    glyph: "backspace",
    jsCode: "Backspace",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5578,
    key_category_id: 81,
    code: "ESC",
    label: "Esc",
    description: null,
    created_at: "2021-12-28T09:53:04.142Z",
    updated_at: "2022-12-16T10:18:32.977Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "Escape",
    tag: null,
    glyph: null,
    jsCode: "Escape",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5579,
    key_category_id: 81,
    code: "TAB",
    label: "Tab",
    description: null,
    created_at: "2021-12-28T09:53:04.153Z",
    updated_at: "2022-12-16T10:18:32.986Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "Tabulation",
    tag: null,
    glyph: null,
    jsCode: "Tab",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5582,
    key_category_id: 81,
    code: "DEL",
    label: "Delete",
    description: null,
    created_at: "2021-12-28T09:53:00.683Z",
    updated_at: "2022-12-16T10:18:31.037Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "Delete",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 6,
    macro: true,
    shape: "block",
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5581,
    key_category_id: 81,
    code: "INSERT",
    label: "Insert",
    description: null,
    created_at: "2021-12-28T09:53:00.533Z",
    updated_at: "2022-12-16T10:18:30.965Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "Insert",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 5,
    macro: true,
    shape: "block",
    comboPickable: true,
    comboTrigger: true,
  },
  // {
  //   id: 6255,
  //   key_category_id: 65,
  //   code: "mo",
  //   label: "MO",
  //   description:
  //     "Momentary layer toggle: Activates the selected layer, but only as long as you keep this key pressed.",
  //   created_at: "2021-12-28T09:53:10.617Z",
  //   updated_at: "2022-12-16T23:38:33.840Z",
  //   deleted: false,
  //   modifiable: false,
  //   shifted: false,
  //   tap: false,
  //   hold: true,
  //   doubleTap: false,
  //   tapHold: true,
  //   searchLabel: null,
  //   tag: "hold",
  //   glyph: "layer_tap",
  //   jsCode: null,
  //   url: null,
  //   os: null,
  //   geometry: null,
  //   params: {
  //     layer: "forwardLayers",
  //   },
  //   models: null,
  //   priority: null,
  //   macro: null,
  //   shape: null,
  //   comboPickable: false,
  //   comboTrigger: false,
  //   layer: null,
  // },
  // {
  //   id: 6257,
  //   key_category_id: 65,
  //   code: "lt",
  //   label: "LT",
  //   description:
  //     "The 'layer-tap' behavior enables a layer when a key is held, and outputs a keypress when the key is only tap for a short time.",
  //   created_at: "2021-12-28T09:53:10.574Z",
  //   updated_at: "2022-12-16T23:38:33.797Z",
  //   deleted: false,
  //   modifiable: false,
  //   shifted: false,
  //   tap: false,
  //   hold: true,
  //   doubleTap: false,
  //   tapHold: false,
  //   searchLabel: null,
  //   tag: "hold",
  //   glyph: "layer_tap",
  //   jsCode: null,
  //   url: null,
  //   os: null,
  //   geometry: null,
  //   params: {
  //     layer: "forwardLayers",
  //     modifier: true,
  //     maxLayers: 16,
  //   },
  //   models: null,
  //   priority: null,
  //   macro: null,
  //   shape: null,
  //   comboPickable: false,
  //   comboTrigger: false,
  //   layer: null,
  // },
  {
    id: 6254,
    key_category_id: 65,
    code: "to",
    label: "Switch To", // replaces all Layer switches because its being calculated in the generate-binding-code
    description:
      "Direct switch to a layer. Works for switching to lower layers as well.",
    created_at: "2021-12-28T09:53:10.582Z",
    updated_at: "2022-12-16T23:38:33.805Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "tap",
    glyph: "layer_tap",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: {
      layer: "otherLayers",
    },
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
    layer: null,
  },
  // {
  //   id: 6254,
  //   key_category_id: 65,
  //   code: "to",
  //   label: "TO",
  //   description:
  //     "Direct switch to a layer. Works for switching to lower layers as well.",
  //   created_at: "2021-12-28T09:53:10.582Z",
  //   updated_at: "2022-12-16T23:38:33.805Z",
  //   deleted: false,
  //   modifiable: false,
  //   shifted: false,
  //   tap: true,
  //   hold: true,
  //   doubleTap: true,
  //   tapHold: true,
  //   searchLabel: null,
  //   tag: "tap",
  //   glyph: "layer_tap",
  //   jsCode: null,
  //   url: null,
  //   os: null,
  //   geometry: null,
  //   params: {
  //     layer: "otherLayers",
  //   },
  //   models: null,
  //   priority: null,
  //   macro: null,
  //   shape: null,
  //   comboPickable: true,
  //   comboTrigger: true,
  //   layer: null,
  // },
  // {
  //   id: 6260,
  //   key_category_id: 65,
  //   code: "tog",
  //   label: "TOG",
  //   description:
  //     "&tog The 'toggle layer' behavior enables a layer until the layer is manually disabled",
  //   created_at: "2021-12-28T09:53:10.599Z",
  //   updated_at: "2022-12-16T23:38:33.822Z",
  //   deleted: false,
  //   modifiable: false,
  //   shifted: false,
  //   tap: true,
  //   hold: false,
  //   doubleTap: false,
  //   tapHold: false,
  //   searchLabel: null,
  //   tag: "tap",
  //   glyph: "layer_tap",
  //   jsCode: null,
  //   url: null,
  //   os: null,
  //   geometry: null,
  //   params: {
  //     layer: "forwardLayers",
  //   },
  //   models: null,
  //   priority: null,
  //   macro: null,
  //   shape: null,
  //   comboPickable: true,
  //   comboTrigger: true,
  //   layer: null,
  // },
  {
    id: 6870,
    key_category_id: 77,
    code: "KP_ASTERISK",
    label: "*",
    description: null,
    created_at: "2021-12-28T09:53:15.667Z",
    updated_at: "2022-12-16T10:18:45.083Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "NumpadMultiply",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6869,
    key_category_id: 77,
    code: "KP_PLUS",
    label: "+",
    description: null,
    created_at: "2021-12-28T09:53:15.659Z",
    updated_at: "2022-12-16T10:18:45.073Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "NumpadAdd",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6859,
    key_category_id: 77,
    code: "KP_COMMA",
    label: ",",
    description: null,
    created_at: "2021-12-28T09:53:15.573Z",
    updated_at: "2022-12-16T10:18:44.984Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "NumpadComma",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6853,
    key_category_id: 77,
    code: "KP_MINUS",
    label: "-",
    description: null,
    created_at: "2021-12-28T09:53:15.526Z",
    updated_at: "2022-12-16T10:18:44.930Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "NumpadSubtract",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6861,
    key_category_id: 77,
    code: "KP_DOT",
    label: ".",
    description: null,
    created_at: "2021-12-28T09:53:15.591Z",
    updated_at: "2022-12-16T10:18:45.005Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "NumpadDecimal",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6864,
    key_category_id: 77,
    code: "KP_SLASH",
    label: "/",
    description: null,
    created_at: "2021-12-28T09:53:15.616Z",
    updated_at: "2022-12-16T10:18:45.035Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "NumpadDivide",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6854,
    key_category_id: 77,
    code: "KP_N0",
    label: "0",
    description: null,
    created_at: "2021-12-28T09:53:15.534Z",
    updated_at: "2022-12-16T10:18:44.939Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad0",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6862,
    key_category_id: 77,
    code: "KP_N1",
    label: "1",
    description: null,
    created_at: "2021-12-28T09:53:15.600Z",
    updated_at: "2022-12-16T10:18:45.016Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad1",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6865,
    key_category_id: 77,
    code: "KP_N2",
    label: "2",
    description: null,
    created_at: "2021-12-28T09:53:15.624Z",
    updated_at: "2022-12-16T10:18:45.045Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad2",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6871,
    key_category_id: 77,
    code: "KP_N3",
    label: "3",
    description: null,
    created_at: "2021-12-28T09:53:15.676Z",
    updated_at: "2022-12-16T10:18:45.095Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad3",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6863,
    key_category_id: 77,
    code: "KP_N4",
    label: "4",
    description: null,
    created_at: "2021-12-28T09:53:15.608Z",
    updated_at: "2022-12-16T10:18:45.025Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad4",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6855,
    key_category_id: 77,
    code: "KP_N5",
    label: "5",
    description: null,
    created_at: "2021-12-28T09:53:15.542Z",
    updated_at: "2022-12-16T10:18:44.947Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad5",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6868,
    key_category_id: 77,
    code: "KP_N6",
    label: "6",
    description: null,
    created_at: "2021-12-28T09:53:15.651Z",
    updated_at: "2022-12-16T10:18:45.063Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad6",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6858,
    key_category_id: 77,
    code: "KP_N7",
    label: "7",
    description: null,
    created_at: "2021-12-28T09:53:15.565Z",
    updated_at: "2022-12-16T10:18:44.975Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad7",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6857,
    key_category_id: 77,
    code: "KP_N8",
    label: "8",
    description: null,
    created_at: "2021-12-28T09:53:15.557Z",
    updated_at: "2022-12-16T10:18:44.965Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad8",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6860,
    key_category_id: 77,
    code: "KP_N9",
    label: "9",
    description: null,
    created_at: "2021-12-28T09:53:15.582Z",
    updated_at: "2022-12-16T10:18:44.996Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "Numpad9",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6867,
    key_category_id: 77,
    code: "KP_ENTER",
    label: "Enter",
    description: null,
    created_at: "2021-12-28T09:53:15.643Z",
    updated_at: "2022-12-16T10:18:45.054Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "NumpadEnter",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6856,
    key_category_id: 77,
    code: "KP_NUMLOCK",
    label: "Numlock",
    description: null,
    created_at: "2021-12-28T09:53:15.549Z",
    updated_at: "2022-12-16T10:18:44.956Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: "numpad",
    glyph: null,
    jsCode: "NumLock",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6846,
    key_category_id: 62,
    code: "N0",
    label: "0",
    description: null,
    created_at: "2021-12-28T09:53:15.466Z",
    updated_at: "2022-12-16T10:18:44.864Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "0",
    tag: null,
    glyph: null,
    jsCode: "Digit0",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6844,
    key_category_id: 62,
    code: "N1",
    label: "1",
    description: null,
    created_at: "2021-12-28T09:53:15.450Z",
    updated_at: "2022-12-16T10:18:44.845Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "1",
    tag: null,
    glyph: null,
    jsCode: "Digit1",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6843,
    key_category_id: 62,
    code: "N2",
    label: "2",
    description: null,
    created_at: "2021-12-28T09:53:15.442Z",
    updated_at: "2022-12-16T10:18:44.836Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "2",
    tag: null,
    glyph: null,
    jsCode: "Digit2",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6851,
    key_category_id: 62,
    code: "N3",
    label: "3",
    description: null,
    created_at: "2021-12-28T09:53:15.509Z",
    updated_at: "2022-12-16T10:18:44.910Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "3",
    tag: null,
    glyph: null,
    jsCode: "Digit3",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6849,
    key_category_id: 62,
    code: "N4",
    label: "4",
    description: null,
    created_at: "2021-12-28T09:53:15.492Z",
    updated_at: "2022-12-16T10:18:44.892Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "4",
    tag: null,
    glyph: null,
    jsCode: "Digit4",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6847,
    key_category_id: 62,
    code: "N5",
    label: "5",
    description: null,
    created_at: "2021-12-28T09:53:15.475Z",
    updated_at: "2022-12-16T10:18:44.873Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "5",
    tag: null,
    glyph: null,
    jsCode: "Digit5",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6852,
    key_category_id: 62,
    code: "N6",
    label: "6",
    description: null,
    created_at: "2021-12-28T09:53:15.517Z",
    updated_at: "2022-12-16T10:18:44.920Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "6",
    tag: null,
    glyph: null,
    jsCode: "Digit6",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6845,
    key_category_id: 62,
    code: "N7",
    label: "7",
    description: null,
    created_at: "2021-12-28T09:53:15.458Z",
    updated_at: "2022-12-16T10:18:44.854Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "7",
    tag: null,
    glyph: null,
    jsCode: "Digit7",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6848,
    key_category_id: 62,
    code: "N8",
    label: "8",
    description: null,
    created_at: "2021-12-28T09:53:15.484Z",
    updated_at: "2022-12-16T10:18:44.882Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "8",
    tag: null,
    glyph: null,
    jsCode: "Digit8",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6850,
    key_category_id: 62,
    code: "N9",
    label: "9",
    description: null,
    created_at: "2021-12-28T09:53:15.500Z",
    updated_at: "2022-12-16T10:18:44.901Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "9",
    tag: null,
    glyph: null,
    jsCode: "Digit9",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6147,
    key_category_id: 67,
    code: "EXCL",
    label: "!",
    description: null,
    created_at: "2021-12-28T09:53:09.672Z",
    updated_at: "2022-12-16T10:18:38.173Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "exclamation",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6156,
    key_category_id: 67,
    code: "DQT",
    label: '"',
    description: null,
    created_at: "2021-12-28T09:53:09.749Z",
    updated_at: "2022-12-16T10:18:38.273Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "double quote",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6142,
    key_category_id: 67,
    code: "HASH",
    label: "#",
    description: null,
    created_at: "2021-12-28T09:53:09.633Z",
    updated_at: "2022-12-16T10:18:38.124Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "hash",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6151,
    key_category_id: 67,
    code: "DOLLAR",
    label: "$",
    description: null,
    created_at: "2021-12-28T09:53:09.707Z",
    updated_at: "2022-12-16T10:18:38.212Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "dollar",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6159,
    key_category_id: 67,
    code: "PERCENT",
    label: "%",
    description: null,
    created_at: "2021-12-28T09:53:09.775Z",
    updated_at: "2022-12-16T10:18:38.301Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "percent",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6158,
    key_category_id: 67,
    code: "AMPERSAND",
    label: "&",
    description: null,
    created_at: "2021-12-28T09:53:09.767Z",
    updated_at: "2022-12-16T10:18:38.292Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "ampersand",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6148,
    key_category_id: 67,
    code: "LPAR",
    label: "(",
    description: null,
    created_at: "2021-12-28T09:53:09.681Z",
    updated_at: "2022-12-16T10:18:38.182Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "left opening parenthesis",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6152,
    key_category_id: 67,
    code: "RPAR",
    label: ")",
    description: null,
    created_at: "2021-12-28T09:53:09.716Z",
    updated_at: "2022-12-16T10:18:38.223Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "closing right parenthesis",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6150,
    key_category_id: 67,
    code: "ASTRK",
    label: "*",
    description: null,
    created_at: "2021-12-28T09:53:09.699Z",
    updated_at: "2022-12-16T10:18:38.202Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "asterisk",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6154,
    key_category_id: 67,
    code: "PLUS",
    label: "+",
    description: null,
    created_at: "2021-12-28T09:53:09.732Z",
    updated_at: "2022-12-16T10:18:38.244Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "plus",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6157,
    key_category_id: 67,
    code: "COLON",
    label: ":",
    description: null,
    created_at: "2021-12-28T09:53:09.758Z",
    updated_at: "2022-12-16T10:18:38.283Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "colon",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6153,
    key_category_id: 67,
    code: "LESS_THAN",
    label: "<",
    description: null,
    created_at: "2021-12-28T09:53:09.724Z",
    updated_at: "2022-12-16T10:18:38.234Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "inferior",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6155,
    key_category_id: 67,
    code: "GREATER_THAN",
    label: ">",
    description: null,
    created_at: "2021-12-28T09:53:09.740Z",
    updated_at: "2022-12-16T10:18:38.254Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "superior",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6160,
    key_category_id: 67,
    code: "QMARK",
    label: "?",
    description: null,
    created_at: "2021-12-28T09:53:09.784Z",
    updated_at: "2022-12-16T10:18:38.312Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "question",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6143,
    key_category_id: 67,
    code: "AT",
    label: "@",
    description: null,
    created_at: "2021-12-28T09:53:09.640Z",
    updated_at: "2022-12-16T10:18:38.134Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "at",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6149,
    key_category_id: 67,
    code: "CARET",
    label: "^",
    description: null,
    created_at: "2021-12-28T09:53:09.689Z",
    updated_at: "2022-12-16T10:18:38.192Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "circumflex",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6141,
    key_category_id: 67,
    code: "UNDERSCORE",
    label: "_",
    description: null,
    created_at: "2021-12-28T09:53:09.625Z",
    updated_at: "2022-12-16T10:18:38.115Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "underscore",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6146,
    key_category_id: 67,
    code: "LBRC",
    label: "{",
    description: null,
    created_at: "2021-12-28T09:53:09.664Z",
    updated_at: "2022-12-16T10:18:38.164Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "left opening curly brace",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6145,
    key_category_id: 67,
    code: "PIPE",
    label: "|",
    description: null,
    created_at: "2021-12-28T09:53:09.656Z",
    updated_at: "2022-12-16T10:18:38.154Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "pipe",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6144,
    key_category_id: 67,
    code: "RBRC",
    label: "}",
    description: null,
    created_at: "2021-12-28T09:53:09.648Z",
    updated_at: "2022-12-16T10:18:38.144Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "right closing curly brace",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 6140,
    key_category_id: 67,
    code: "TILDE",
    label: "~",
    description: null,
    created_at: "2021-12-28T09:53:09.617Z",
    updated_at: "2022-12-16T10:18:38.105Z",
    deleted: false,
    modifiable: false,
    shifted: true,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "tilde",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5636,
    key_category_id: 66,
    code: "DOT",
    label: ".",
    description: null,
    created_at: "2021-12-28T09:53:04.751Z",
    updated_at: "2022-12-16T10:18:33.521Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "period",
    tag: null,
    glyph: null,
    jsCode: "Period",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 1,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5632,
    key_category_id: 66,
    code: "COMMA",
    label: ",",
    description: null,
    created_at: "2021-12-28T09:53:04.716Z",
    updated_at: "2022-12-16T10:18:33.482Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "comma",
    tag: null,
    glyph: null,
    jsCode: "Comma",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 2,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5633,
    key_category_id: 66,
    code: "SEMICOLON",
    label: ";",
    description: null,
    created_at: "2021-12-28T09:53:04.725Z",
    updated_at: "2022-12-16T10:18:33.491Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "semi colon",
    tag: null,
    glyph: null,
    jsCode: "Semicolon",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 3,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5631,
    key_category_id: 66,
    code: "EQUAL",
    label: "=",
    description: null,
    created_at: "2021-12-28T09:53:04.707Z",
    updated_at: "2022-12-16T10:18:33.473Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "equal",
    tag: null,
    glyph: null,
    jsCode: "Equal",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 4,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5626,
    key_category_id: 66,
    code: "MINUS",
    label: "-",
    description: null,
    created_at: "2021-12-28T09:53:04.659Z",
    updated_at: "2022-12-16T10:18:33.427Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "minus",
    tag: null,
    glyph: null,
    jsCode: "Minus",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 5,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5634,
    key_category_id: 66,
    code: "SINGLE_QUOTE",
    label: "'",
    description: null,
    created_at: "2021-12-28T09:53:04.734Z",
    updated_at: "2022-12-16T10:18:33.503Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "single quote",
    tag: null,
    glyph: null,
    jsCode: "Quote",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 6,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5639,
    key_category_id: 66,
    code: "GRAVE",
    label: "`",
    description: null,
    created_at: "2021-12-28T09:53:04.778Z",
    updated_at: "2022-12-16T10:18:33.547Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "backquote",
    tag: null,
    glyph: null,
    jsCode: "Backquote",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 7,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5638,
    key_category_id: 66,
    code: "LBKT",
    label: "[",
    description: null,
    created_at: "2021-12-28T09:53:04.768Z",
    updated_at: "2022-12-16T10:18:33.539Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "left opening bracket",
    tag: null,
    glyph: null,
    jsCode: "BracketLeft",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 8,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5635,
    key_category_id: 66,
    code: " RBKT",
    label: "]",
    description: null,
    created_at: "2021-12-28T09:53:04.743Z",
    updated_at: "2022-12-16T10:18:33.512Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "right closing bracket",
    tag: null,
    glyph: null,
    jsCode: "BracketRight",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 9,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5628,
    key_category_id: 66,
    code: "BACKSLASH",
    label: "\\",
    description: null,
    created_at: "2021-12-28T09:53:04.680Z",
    updated_at: "2022-12-16T10:18:33.445Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "backslash",
    tag: null,
    glyph: null,
    jsCode: "Backslash",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 10,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5637,
    key_category_id: 66,
    code: "SLASH",
    label: "/",
    description: null,
    created_at: "2021-12-28T09:53:04.760Z",
    updated_at: "2022-12-16T10:18:33.530Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "slash",
    tag: null,
    glyph: null,
    jsCode: "Slash",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 11,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5627,
    key_category_id: 66,
    code: "CAPSLOCK",
    label: "Caps lock",
    description: null,
    created_at: "2021-12-28T09:53:04.670Z",
    updated_at: "2022-12-16T10:18:33.436Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "Capslock",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5629,
    key_category_id: 66,
    code: "NON_US_HASH",
    label: "Non-US # and ~",
    description: null,
    created_at: "2021-12-28T09:53:04.689Z",
    updated_at: "2022-12-16T10:18:33.454Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "hash tilde",
    tag: null,
    glyph: null,
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5630,
    key_category_id: 66,
    code: "NON_US_BACKSLASH",
    label: "Non-US \\ and |",
    description: "Non-US backslash and pipe",
    created_at: "2021-12-28T09:53:04.698Z",
    updated_at: "2022-12-16T23:38:30.658Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "backslash pipe",
    tag: null,
    glyph: null,
    jsCode: "IntlBackslash",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5002,
    key_category_id: 121,
    code: "none",
    label: "None",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: false, // defaults if neither tap or held are selected
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5012,
    key_category_id: 121,
    code: "trans",
    label: "Transparent",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5013,
    key_category_id: 1256,
    code: "BT_SEL 0 ",
    label: "BT Select 1",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5014,
    key_category_id: 1256,
    code: "BT_SEL 1",
    label: "BT Select 2",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5015,
    key_category_id: 1256,
    code: "BT_SEL 2",
    label: "BT Select 3",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5016,
    key_category_id: 1256,
    code: "BT_SEL 3",
    label: "BT Select 4",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5017,
    key_category_id: 1256,
    code: "BT_SEL 4",
    label: "BT Select 5",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5019,
    key_category_id: 1256,
    code: "BT_CLR",
    label: "BT clear",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5020,
    key_category_id: 1256,
    code: "BT_NXT",
    label: "BT next",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5021,
    key_category_id: 1256,
    code: "BT_PRV",
    label: "BT previous",
    description: null,
    created_at: "2021-12-28T09:52:57.253Z",
    updated_at: "2021-12-28T09:52:57.253Z",
    deleted: false,
    modifiable: false,
    shifted: false,
    tap: true,
    hold: false,
    doubleTap: false,
    tapHold: false,
    searchLabel: null,
    tag: null,
    glyph: "none",
    jsCode: null,
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: null,
    shape: null,
    comboPickable: false,
    comboTrigger: false,
  },
  {
    id: 5333,
    key_category_id: 76,
    code: "LEFT",
    label: "Arrow left",
    description: null,
    created_at: "2021-12-28T09:53:00.622Z",
    updated_at: "2022-12-16T10:18:31.011Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: "arrow_left",
    jsCode: "ArrowLeft",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 1,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5325,
    key_category_id: 76,
    code: "UP",
    label: "Arrow up",
    description: null,
    created_at: "2021-12-28T09:53:00.480Z",
    updated_at: "2022-12-16T10:18:30.942Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: "arrow_up",
    jsCode: "ArrowUp",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 2,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5334,
    key_category_id: 76,
    code: "RIGHT",
    label: "Arrow right",
    description: null,
    created_at: "2021-12-28T09:53:00.646Z",
    updated_at: "2022-12-16T10:18:31.020Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: "arrow_right",
    jsCode: "ArrowRight",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 3,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5330,
    key_category_id: 76,
    code: "DOWN",
    label: "Arrow down",
    description: null,
    created_at: "2021-12-28T09:53:00.560Z",
    updated_at: "2022-12-16T10:18:30.982Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: "arrow_down",
    jsCode: "ArrowDown",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 4,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5328,
    key_category_id: 76,
    code: "INSERT",
    label: "Ins",
    description: null,
    created_at: "2021-12-28T09:53:00.533Z",
    updated_at: "2022-12-16T10:18:30.965Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "Insert",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 5,
    macro: true,
    shape: "block",
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5336,
    key_category_id: 76,
    code: "DELETE",
    label: "Del",
    description: null,
    created_at: "2021-12-28T09:53:00.683Z",
    updated_at: "2022-12-16T10:18:31.037Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "Delete",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 6,
    macro: true,
    shape: "block",
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5327,
    key_category_id: 76,
    code: "HOME",
    label: "Home",
    description: null,
    created_at: "2021-12-28T09:53:00.518Z",
    updated_at: "2022-12-16T10:18:30.958Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "Home",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 7,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5335,
    key_category_id: 76,
    code: "END",
    label: "End",
    description: null,
    created_at: "2021-12-28T09:53:00.671Z",
    updated_at: "2022-12-16T10:18:31.029Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "End",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: 8,
    macro: true,
    shape: "block",
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5332,
    key_category_id: 76,
    code: "K_APP",
    label: "Application",
    description: null,
    created_at: "2021-12-28T09:53:00.602Z",
    updated_at: "2022-12-16T10:18:31.000Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "application",
    tag: null,
    glyph: "application",
    jsCode: "ContextMenu",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5329,
    key_category_id: 76,
    code: "PAGE_DOWN",
    label: "PgDn",
    description: null,
    created_at: "2021-12-28T09:53:00.546Z",
    updated_at: "2022-12-16T10:18:30.974Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "page",
    tag: null,
    glyph: null,
    jsCode: "PageDown",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5324,
    key_category_id: 76,
    code: "PAGE_UP",
    label: "PgUp",
    description: null,
    created_at: "2021-12-28T09:53:00.454Z",
    updated_at: "2022-12-16T10:18:30.934Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: "page",
    tag: null,
    glyph: null,
    jsCode: "PageUp",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5326,
    key_category_id: 76,
    code: "SCROLLLOCK",
    label: "Scroll lock",
    description: null,
    created_at: "2021-12-28T09:53:00.494Z",
    updated_at: "2022-12-16T10:18:30.950Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "ScollLock",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
  {
    id: 5331,
    key_category_id: 76,
    code: "PRINTSCREEN",
    label: "Print screen",
    description:
      "Also known as Print Screen. Alt+SysRq would give you the Linux Magic SysRq combo on one key.",
    created_at: "2021-12-28T09:53:00.577Z",
    updated_at: "2022-12-16T23:38:29.220Z",
    deleted: false,
    modifiable: true,
    shifted: false,
    tap: true,
    hold: true,
    doubleTap: true,
    tapHold: true,
    searchLabel: null,
    tag: null,
    glyph: null,
    jsCode: "PrintScreen",
    url: null,
    os: null,
    geometry: null,
    params: null,
    models: null,
    priority: null,
    macro: true,
    shape: null,
    comboPickable: true,
    comboTrigger: true,
  },
];
