export class Layer {
  constructor(label, index) {
    this.index = index;
    this.label = label;
    this.bindings = [
      {
        index: 0,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 1,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 2,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 3,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 4,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 5,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 6,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 7,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 8,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 9,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 10,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 11,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 12,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 13,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 14,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 15,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 16,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 17,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 18,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 19,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 20,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 21,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 22,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 23,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 24,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 25,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 26,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 27,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 28,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 29,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 30,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 31,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 32,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 33,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 34,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
      {
        index: 35,
        label: "",
        tap: {
          id: 5002,
          key_category_id: 121,
          code: "none",
          label: "None",
          description: null,
          created_at: "2021-12-28T09:52:57.253Z",
          updated_at: "2021-12-28T09:52:57.253Z",
          deleted: false,
          modifiable: false,
          shifted: false,
          tap: true,
          hold: false,
          doubleTap: false,
          tapHold: false,
          searchLabel: null,
          tag: null,
          glyph: "none",
          jsCode: null,
          url: null,
          os: null,
          geometry: null,
          params: null,
          models: null,
          priority: null,
          macro: null,
          shape: null,
          comboPickable: false,
          comboTrigger: false,
          modifiers: [],
        },
        held: {
          modifiers: [],
        },
      },
    ];
  }
}
